name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: buchstabensuppe
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build web output
        run: |
          nix-build -A deploy doc/web.nix
          ./result -w tmp
      - name: Deploy output to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.5
        with:
          branch: gh-pages
          clean: true
          folder: tmp
